muxinc/mux-stats-sdk-avplayer

MUXSDKStats/MUXSDKStats/MUXSDKStats.h
- Entire implementation in `MUXSDKImaListener.h` is wrapped in `#if TARGET_OS_IOS`
=> MUXSDKImaListener is not available in tvOS

apps/video-demo/video-demo/VideoPlayerController.swift
* we no longer are the time observer - that was removed, so let's not crash in the cleanUp() method
=> Fix swift video-demo app crash when player closes

.gitignore, apps/DemoApp/DemoApp.xcodeproj/project.pbxproj, apps/DemoApp/DemoApp.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme, apps/DemoApp/DemoApp.xcodeproj/xcshareddata/xcschemes/DemoAppUITests.xcscheme, apps/DemoApp/DemoApp/ViewController.m, apps/DemoApp/DemoAppUITests/DemoAppUITests.m, apps/DemoApp/DemoAppUITests/Info.plist, apps/DemoApp/run-tests.sh
https://zube.io/muxinc/mux/c/13153
* Adds a new UI test target for the DemoApp. Adds a simple test case that launches the app and plays one video. 
* Updates the buildkite script to install Mux-Stats-AVPlayer SDK built from a previous step and run the tests. 
```
Testing started
--
  | 2020-10-27 17:06:17.313 xcodebuild[33482:3381246]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
  | /Users/administrator/Library/Developer/Xcode/DerivedData/DemoApp-eknlxvcjybxdqcchzaxhlhuxpjzn/Logs/Test/Test-DemoApp-2020.10.27_17-06-10--0700.xcresult/Staging/1_Test/Diagnostics/DemoAppUITests-7E7F6387-BFF9-4AAF-90B5-92E05A3D1F12/DemoAppUITests-C4C34BAD-489D-41C5-BF50-135205AAF14B/Session-DemoAppUITests-2020-10-27_170617-NKL8o5.log
  | 2020-10-27 17:06:17.313 …
```
=> Adds an automated test for DemoApp that launches the app and plays one video

apps/DemoApp/DemoApp.xcodeproj/project.pbxproj, apps/DemoApp/Podfile, apps/DemoApp/Podfile.lock
The reason the UI tests were failing to pull in the statically linked Mux Core previously was because the DemoApp Podfile had not been configured to use static frameworks. This PR fixes that: https://buildkite.com/mux/stats-sdk-avplayer/builds?branch=nidhik%2Fstatics
View from UI test: https://dashboard.mux.com/environments/k0vjj8/views/zb9MAA0ty1r0x2SENlSJw9hy3xty19416qeL
=> update demo app to pull in static mux core

apps/DemoApp/run-tests.sh
I noticed in another Buildkite run that our UI tests sometimes pass until I manually reset the simulators on the build machine. 
I realized this is because there are some code paths that only get exercised if certain events happen while the video plays - for example, `renditionchange` events. There seems to be some sort of on device caching of state (maybe `AVPlayer` does this or maybe it's a network level thing?) because unless you reset the simulator, the same events for each video do not get always fire. 
This makes sure to shutdown and erase all simulators before each test run.
=> Erase simulators before tests run

MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.m
https://zube.io/muxinc/mux/c/17447
If the AVPlayerItem is released and we are still observing it, it can lead to this crash:
```
KVO_IS_RETAINING_ALL_OBSERVERS_OF_THIS_OBJECT_IF_IT_CRASHES_AN_OBSERVER_WAS_OVERRELEASED_OR_SMASHED
```
I recently added a new KVO observer for the player item's `playbackBufferEmpty` key without the corresponding call to remove it.
=> Safely remove `playbackBufferEmpty` observer

.buildkite/pipeline.yml, .buildkite/unit-tests.sh, MUXSDKStats/MUXSDKStats.xcodeproj/xcshareddata/xcschemes/MUXSDKStats.xcscheme, MUXSDKStats/MUXSDKStats.xcodeproj/xcshareddata/xcschemes/MUXSDKStatsTv.xcscheme
https://zube.io/muxinc/mux/c/19047
Takes a similar approach to what we did here, with some additional steps for Cocoapods: https://github.com/muxinc/mux-stats-sdk-objc/pull/111/
See: https://buildkite.com/mux/stats-sdk-avplayer/builds/305#
=> Run unit tests as part of the BuildKite pipeline

MUXSDKStats/MUXSDKStats/MUXSDKStats.m
Mux Viewer ID should use a random uuid, not IDFV on iOS
https://zube.io/muxinc/mux-ios-sdks/c/3
=> Replace identifierForVendor with alternative UUID

MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.m, MUXSDKStats/MUXSDKStats/MUXSDKStats.m
There is a race condition in MUXSDKStats class, specifically when the monitorAVPlayerViewController method is called. Currently the initSDK method is the one that calls the `detectConnectionType` method from MUXSDKConnection (posts a notification when connection type is identified), this init is called at the very beginning of the method, after that the `attachAVPlayer` method of the new binding is called (from here we start listening for connection type notifications) and at this point the notification of the connection type might have already been broadcasted, which is the case when the connection type isn’t reflected in the dashboard.
`detectConnectionType` call has been moved out of MUXSDKStats and now is called when `attachAVPlayer` from `MUXSDKPlayerBinding` is called, right after …
=> Fix race condition when checking connection type

apps/DemoApp/DemoApp/ViewController.m, apps/DemoApp/DemoAppUITests/DemoAppUITests.m
[ch712] Issue: mux-stats-sdk-avplayer does not create new view when video changes in AVQueuePlayer.
Solution:
- Confirmed that AVQueuePlayer is working as expected.
- Fix DemoApp implementation for testAVQueuePlayer to call MUXSDKStats videoChangeForPlayer: withVideoData when getting the AVPlayerItemDidPlayToEndTimeNotification.
- Add UITest case for testAVQueuePlayer.
=> [ch712] test AVQueuePlayer

apps/DemoApp/DemoApp/ViewController.m, apps/DemoApp/DemoAppUITests/DemoAppUITests.m
https://app.shortcut.com/ios-sdks/story/11638/avplayer-2-8-0-does-not-dispatch-playing-after-seeked-event-on-programmatic-seeks
Adds two automated UI test cases for seeking so we can make sure the views have comparable metrics. 
1. programmatic/auto seek using the `seekToTime:` API. Example: https://dashboard.mux.com/organizations/ffhei0/environments/k0vjj8/views/aPgABMPtNx87xPCRm6Ik9NC5yYUpD0JWjMD6
2. Uses slider UI control. Example: https://dashboard.mux.com/organizations/ffhei0/environments/k0vjj8/views/0RVnKALh022BkVU5MAuMd2SdVlhb7llbRN36
=> Add seek test cases

MUXSDKStats/MUXSDKStats/MUXSDKCustomerCustomDataStore.h, MUXSDKStats/MUXSDKStats/MUXSDKCustomerCustomDataStore.m, MUXSDKStats/MUXSDKStats/MUXSDKCustomerPlayerDataStore.h, MUXSDKStats/MUXSDKStats/MUXSDKCustomerPlayerDataStore.m, MUXSDKStats/MUXSDKStats/MUXSDKCustomerVideoDataStore.h, MUXSDKStats/MUXSDKStats/MUXSDKCustomerVideoDataStore.m, MUXSDKStats/MUXSDKStats/MUXSDKCustomerViewDataStore.h, MUXSDKStats/MUXSDKStats/MUXSDKCustomerViewDataStore.m, MUXSDKStats/MUXSDKStats/MUXSDKPlayerBindingManager.m, MUXSDKStats/MUXSDKStatsTests/MUXSDKStatsTests.m
https://app.shortcut.com/ios-sdks/story/10841/clear-customer-metadata-stored-under-playername-when-destroy-player-is-called
We need to make sure to clear out all customer metadata when a player monitor is destroyed so that the same player name may be reused.
=> Clear customer metadata stored under `playerName` when `destroyPlayer` is called

MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.m
These changes prevent a crash caused by casting `[AVMetadataItem key]` to an `NSString` without checking the type first.
`[AVMetadataItem key]` is defined as `id<NSObject, NSCopying>` since it can be a type other than `NSString`. 
I'm witnessing crashes in v1.12.0 due to `[AVMetadataItem key]` returning an `NSNumber` and the line `[keyString hasPrefix:MUXSessionDataPrefix]` throws an `unrecognized selector sent to instance` exception.
These changes check that  `[AVMetadataItem key]` is an `NSString` before casting to it.
=> Fix crash in `AVMetadataItem` inspection

.github/workflows/build-and-test.yml, apps/DemoApp/run-tests-big-sur.sh, apps/DemoApp/run-tests.sh
Update macOS version to Ventura
Use existing simulator when running tests
Use Xcode 13.4.1 to test iOS 15 and use the right iOS 15 version
Remove link to older simulators from GitHub Action config
=> ci: update iOS Simulator and macOS versions

MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.m, MUXSDKStats/MUXSDKStatsTests/MUXSDKStatsTests.m
* Log warning when attempting viewend
* Adjust unit test logic to destroy player before checking event sequence
* Include viewend as expected event during testing
=> Add state check when dispatching viewend

MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.h, MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.m
Removing these because these dimensions can only be set once. As a result once the first value is received by the server the player software name and version cannot be altered by the next beacon in sequence.
Reflect that restriction in the API by allowing them to only be set once at initialization time.
To minimize exposed API surface this PR removes both of the newly added getters too, we can add them back as `readonly` properties in a future release.
=> fix: remove public accessors for player software name and version

Sources/MUXSDKStatsObjc/MUXSDKPlayerBinding.h, Sources/MUXSDKStatsObjc/MUXSDKStats.h, Sources/MUXSDKStatsObjc/MUXSDKStats.m, Tests/MUXSDKStatsObjcTests/MUXSDKStatsTests.m
This PR also converts the inline API docs to the docc format. Down the road we should be able to generate static documentation using the Xcode documentation compiler.
=> chore: remove deprecated interfaces

Sources/MUXSDKStatsObjc/MUXSDKStats.h, Sources/MUXSDKStatsObjc/MUXSDKStats.m
Changes `MUXSDKStats` to use the conventionally standard Objective-C `BOOL` type.
=> fix: use right BOOL type

MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.m
additionally, separate check for player paused
=> fix: refrain from sending error dimensions on non-error events

MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.m, apps/MUXSDKStatsExampleSPM/MUXSDKStatsExampleSPM.xcodeproj/project.pbxproj, apps/MUXSDKStatsExampleSPM/MUXSDKStatsExampleSPM.xctestplan, apps/MUXSDKStatsExampleSPM/MUXSDKStatsExampleSPM/Base.lproj/Main.storyboard, apps/MUXSDKStatsExampleSPM/MUXSDKStatsExampleSPMUITests/MUXSDKStatsExampleSPMUITests.swift
- fix: dispatch view end when AVPlayerItem changes
- fix: skip dispatching view init when player has no player item
=> fix: improve AVPlayer currentItem transition handling

.buildkite/pipeline.yml, MUXSDKStats/BuildConfiguration/MUXSDKStats.xcconfig, MUXSDKStats/BuildConfiguration/MUXSDKStatsBase.xcconfig, MUXSDKStats/BuildConfiguration/MUXSDKStatsTv.xcconfig, MUXSDKStats/BuildConfiguration/MUXSDKStatsVision.xcconfig, MUXSDKStats/MUXSDKStats.xcodeproj/project.pbxproj, MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.m, MUXSDKStats/MUXSDKStats/MUXSDKStats.xcconfig, scripts/create-dynamic-xcframework.sh, scripts/create-static-xcframework.sh
=> build: add xcconfig, to simplify version updates

MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.m
* dispatch a viewend automatically and tear down player monitoring when the application shuts down
* remove commented out log lines
=> fix: tear down view on hard application termination

scripts/build-package.sh, scripts/run-ci-tests.sh, scripts/run-integration-tests.sh, scripts/unit-test-package.sh
In _some_ of our scripts, checking the `xcodebuild` status happens after re-enabling exit on error (via `set -e`), and so it's actually checking the result of `set -e`. As a result, some things could fail silently in CI.
I noticed this when some in-progress code suspiciously passed CI checks.
=> Fix checking xcodebuild exit code in scripts

Fixtures/IntegrationTests/IntegrationTests/IntegrationTests.swift
Switched from expectation to [Issue.record + return] since expect wasn't stopping execution
=> Minor fix on integration tests to break while loop.

Sources/MUXSDKStats/MUXSDKPlayerBinding.m
This PR tries to fix a customer reported issue causing main thread to stall (for more than 2 seconds).
[From the Apple docs](https://developer.apple.com/documentation/avfoundation/avasynchronouskeyvalueloading/loadvaluesasynchronously(forkeys:completionhandler:)?language=objc)
> Regardless of the number of keys specified, the system calls the completion handler only once per invocation of this method. The system calls this method:
> 
> Synchronously if the asset already loaded the specified keys, or if an I/O error or other format-related error occurs immediately.
> 
> Asynchronously when the values of the specified keys become loaded, if a loading error occurs at a later stage of processing, or you cancel loading. The system calls the closure on a background queue, so you should dispatch …
=> bug fix - Load Values Asynchronously For Keys causes stall

Sources/MUXSDKStats/MUXSDKPlayerBinding.m, Tests/MUXSDKStatsTests/MUXSDKStatsTests.m
Fully disables the Objective-C implementation of rendition change tracking video source width/height when the Swift implementation is active. Notably this avoids the `-getSourceDimensions` method which is wrapped in a big `@try/@catch`. Also avoids a few code paths related to rendition bitrate tracking.
=> More explicit Swift monitor enable/disable

Package.swift, Sources/MUXSDKStatsInternal/AVPlayerItem+AccessLog.swift, Sources/MUXSDKStatsInternal/Future+async.swift, Sources/MUXSDKStatsInternal/MUXSDKVideoData.swift, Sources/MUXSDKStatsInternal/PlayerMonitor.swift, Sources/MUXSDKStatsInternal/Publishers+AVPlayerItem.swift, Sources/MUXSDKStatsInternal/Publishers+AsyncSequence.swift, Sources/MUXSDKStatsInternal/Task+Timeout.swift, Tests/MUXSDKStatsInternalTests/Task+TimeoutTests.swift, scripts/build-package.sh
Updates package to reflect Xcode 16 requirements (swift-tools-version:6.0), enables strict concurrency checking, and makes related updates to comply with this strict compiler mode.
No unsafe or escape hatch solutions were used except for getting around the unnecessarily strict sendability requirement on `MainActor.assumeIsolated`, and comments were added to explain.
Tested locally as well with Xcode 16.0, which is the oldest version that can make App Store submissions.
=> Strict Swift Concurrency

Sources/MUXSDKStats/MUXSDKPlayerBinding.m
When registering for and receiving Key-Value Observing change notifications, a unique context pointer can be used. A common way to get a unique pointer for each logically separate use of this API is to assign a `static void *` the address of itself. Here it seems we have a duplicate (probably copy/paste error) so effectively we're sharing a "unique" id for two separate usages.
In practice, these two usages will never overlap because:
* one is for the AVPlayer object and the other is for the AVPlayerItem object
* in the change handler we don't try to access the object or property
* in the change handler we end up calling the same method in either case
* when deregistering we don't use contexts at all (though it is recommended)
Of course if _any_ of that changed we'd be in trouble.
=> fix duplicated "unique" KVO context pointer

Fixtures/IntegrationTests/IntegrationTests/IntegrationTests.swift
Integration test that analyzes whether the source change was performed correctly.
Test steps:
- Start playing a video (HLS)
- Wait 5 seconds
- Change the Video URL (to a new HLS)
- Play the new video
- Wait 5 second
The test will be successful if when changing the video, a ViewEnd event is triggered and the DataEvents have the new source.
This PR closes [#328](https://github.com/muxinc/psdks_and_dev_rel_team/issues/328)
=> Changing the Source Integration Test

Fixtures/UnitTests/UnitTests.xcodeproj/project.pbxproj, Sources/MUXSDKStats/MUXSDKBandwidthMetricData+MUXSDKAccessLog.m, Tests/MUXSDKStatsTests/MUXSDKBandwidthMetricDataTests.m
The previous implementation could cause a crash when `pathExtension` was `nil`. I've just reverted the `UTType` stuff since it's not especially valuable in this best-effort fallback helper method.
=> Fix crash & simplify access log URI handling

Fixtures/IntegrationTests/IntegrationTests/IntegrationTests.swift, Tests/MUXSDKStatsTests/MUXSDKStatsTests.m
Uses well-known Mux assets for integration tests, modifying tests for timing to work with the new assets.
Additionally integration tests were themselves crashing, leading to useless results. This PR also changes the force-unwrapping of optionals to throwing `#require`s, but with no other attempt to change behavior.
=> Use Mux assets in tests

Package.swift, Tests/MUXSDKStatsInternalTests/MuxTimeValueConvertibleTests.swift, Tests/MUXSDKStatsInternalTests/Task+TimeoutTests.swift, scripts/MUXSDKStatsFramework.xcodeproj/project.pbxproj
The internal Swift target was already compliant, there were just some tests that needed updating. They've been updated with comments.
=> Use full Swift 6 mode

Sources/MUXSDKStats/MUXSDKPlayerBinding.m
This `getVideoBounds` is not used internally or exposed publicly.
=> Remove unused getVideoBounds from bindings
